version: 2.1
jobs:
  build:
    machine: true
    steps:
      - checkout
      - run: sudo add-apt-repository -y ppa:hvr/ghc
      - run: sudo apt-get update
      - run: sudo apt-get -y install cabal-install-head
      - run: sudo apt-get -y install ghc-8.6.2
      - run: sudo ln -s /opt/ghc/bin/ghc-8.6.2 /bin/ghc
      - restore_cache:
          name: Restore cached dependencies
          keys:
            - oak-v1{{ checksum "oak.cabal" }}
      - run:
          name: Update Hackage
          command: /opt/cabal/bin/cabal new-update
      - run:
          name: Build
          command: /opt/cabal/bin/cabal new-build
      - save_cache:
          name: Cache dependencies
          key: oak-v1{{ checksum "oak.cabal" }}
          paths:
            - ./dist/
            - ./dist-newstyle/
            - ~/.cabal/
      - store_artifacts:
          path: ./dist-newstyle/build/x86_64-linux/ghc-8.6.2/oak-1.3.1.0/x/oak/build/oak/oak
          destination: oak
